#!/bin/sh

echo "Automatic generator of OpenShift installation configuration file (install-config.yaml) for AWS IPI installation"

echo

# check mandatory variables
if [ -z "$CLUSTER_NAME" ]; then
  echo "CLUSTER_NAME is not set!"
  exit 1
fi

if [ -z "$OPENSHIFT_BASE_DOMAIN" ]; then
  echo "OPENSHIFT_BASE_DOMAIN is not set!"
  exit 2
fi

if [ -z "$AWS_DEFAULT_REGION" ]; then
  echo "AWS_DEFAULT_REGION is not set!"
  exit 3
fi

if [ -z "$OPENSHIFT_PULL_SECRET" ]; then
  echo "OPENSHIFT_PULL_SECRET is not set!"
  exit 4
fi

echo "Base domain         : $OPENSHIFT_BASE_DOMAIN"
echo "Cluster name        : $CLUSTER_NAME"
echo "Cluster base domain : $CLUSTER_NAME.$OPENSHIFT_BASE_DOMAIN"

SCRIPT_DIRECTORY=$(dirname "$0")

mkdir -p $SCRIPT_DIRECTORY/clusters/$CLUSTER_NAME

# optional: source the export command with the VPC subnets IDs (VPC_SUBNETS environment variable) generated by Ansible
if [ -e "$SCRIPT_DIRECTORY/clusters/$CLUSTER_NAME/vpc_subnets_export" ]; then
  echo "Custom VPC subnets  : $SCRIPT_DIRECTORY/clusters/$CLUSTER_NAME/vpc_subnets_export"
  source $SCRIPT_DIRECTORY/clusters/$CLUSTER_NAME/vpc_subnets_export
fi

# define SUBNETS only if VPC_SUBNETS is set
SUBNETS=
if [ ! -z "$VPC_SUBNETS" ]; then
  SUBNETS=$(echo -e "\n    subnets:$VPC_SUBNETS")
fi

# allow single node OpenShift clusters by setting MASTERS_COUNT to 1 (otherwise use 3 as a default)
if [ -z "$MASTERS_COUNT" ]; then
  echo "Masters count       : 3 (override with MASTERS_COUNT environment variable)"
  MASTERS_COUNT=3
else
  echo "Masters count       : $MASTERS_COUNT (set by MASTERS_COUNT environment variable)"
fi

# write the install-config.yaml
cat <<EOF > $SCRIPT_DIRECTORY/clusters/$CLUSTER_NAME/install-config.yaml
apiVersion: v1
baseDomain: $CLUSTER_NAME.$OPENSHIFT_BASE_DOMAIN
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: $MASTERS_COUNT
metadata:
  name: $CLUSTER_NAME
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: $AWS_DEFAULT_REGION$SUBNETS
publish: External
pullSecret: '$OPENSHIFT_PULL_SECRET'
EOF

echo
echo "OpenShift install config written to '$SCRIPT_DIRECTORY/clusters/$CLUSTER_NAME/install-config.yaml'"
echo
echo "Customize this config if needed then use following command"
echo
echo "  openshift-install create cluster --dir $SCRIPT_DIRECTORY/clusters/$CLUSTER_NAME --log-level=INFO"
echo
echo "to start installation of OpenShift cluster"
