- name: Create Load Balancers and DNS records
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Check whether CLUSTER_NAME environment variable exists
    ansible.builtin.fail:
      msg: "The CLUSTER_NAME environment variable is not set!"
    when: not (lookup('env', "CLUSTER_NAME"))
  - name: Check whether OPENSHIFT_BASE_DOMAIN environment variable exists
    ansible.builtin.fail:
      msg: "The OPENSHIFT_BASE_DOMAIN environment variable is not set!"
    when: not (lookup('env', "OPENSHIFT_BASE_DOMAIN"))
  - name: Set cluster name
    ansible.builtin.set_fact:
      cluster_name: "{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}"
  - name: Set OpenShift base domain
    ansible.builtin.set_fact:
      openshift_base_domain: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_BASE_DOMAIN') }}"

- name: Configure Load Balancers
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
  - name: Define OpenShift Nodes IPs
    role: ocp4-ips
  - name: Load Balancers
    role: ocp4-loadbalancers

- name: Configure DNS
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
  - name: DNS
    role: ocp4-dns