apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-secret-stackrox
  namespace: rhacs-operator
placementRef:
  name: not-in-cluster
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-advanced-managed-cluster-security
  kind: Policy
  apiGroup: policy.open-cluster-management.io