apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-secret-stackrox
  namespace: rhacs-operator
placementRef:
  name: placement-sc
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-advanced-managed-cluster-security
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-sc
  namespace: rhacs-operator
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}
      - {key: local-cluster, operator: DoesNotExist}
