---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-advanced-cluster-security-central
  namespace: rhacs-operator
placementRef:
  name: placement-policy-advanced-cluster-security-central
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-advanced-cluster-security-central
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: rhacs-operator
  name: placement-policy-advanced-cluster-security-central
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}
