apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: open-cluster-management
  name: in-cluster
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: rhacs-operator
  name: in-cluster
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}