apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: rhacs-operator
  name: not-in-cluster
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}
      - {key: local-cluster, operator: DoesNotExist}