apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: {{ .Values.clusterName }}-{{ .Values.version | replace "." "" }}-{{ .Values.channel | replace "." "" }}
  namespace: {{ .Values.clusterName }}
spec:
  desiredCuration: upgrade
  install:
    towerAuthSecret: awx- //will be normalized
    prehook: []
    posthook: []
  upgrade:
    channel: {{ .Values.channel }}
    desiredUpdate: {{ .Values.version }}
    towerAuthSecret: awx- //will be normalized
    prehook:
      - name: ACM  Upgrade Prechecks //will be normalized
        extra_vars:
          clusterName: {{ .Values.clusterName }}
    posthook: []
