apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rhacs-secrets-in-managed-clusters
  namespace: rhacs-operator
placementRef:
  name: managed-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: rhacs-secrets
  kind: Policy
  apiGroup: policy.open-cluster-management.io