- name: Install Quay
  hosts: bastion
  gather_facts: false
  vars:
    quay_directory: ~/quay
    quay_root: ~/quay/install
  roles:
  - role: ocp4-pull-secret
  - role: quay
  tasks:
  - name: Download Quay root CA
    ansible.builtin.fetch:
      src: "{{ quay_root }}/quay-rootCA/rootCA.pem"
      dest: ../../ocp4/quay_ca.pem
      flat: true
